### ISSUE TITLE
wallet/rules: REVEAL output address is not enforced by consensus rules

### ISSUE THREAD

**Issue by pinheadmz** [handshake-org/hsd#151]
If I'm reading this correctly, when the wallet makes a `REVEAL` covenant tx, it sends the `REVEAL` to the same address in the `BID` covenant output that it is "spending" from:

`makeReveal()`:

https://github.com/handshake-org/hsd/blob/b32c27bbb05e69b86c0e80aea3ecc394c5589186/lib/wallet/wallet.js#L1753-L1754

However, in the part of the code where covenant addresses are checked, this does not seem to be required. I would expect to see that check in here:

https://github.com/handshake-org/hsd/blob/b32c27bbb05e69b86c0e80aea3ecc394c5589186/lib/covenants/rules.js#L1186-L1217

For reference, there are some covenant->covenant transactions where address unity is enforced.

`REVEAL` -> `REGISTER` must have same address:

https://github.com/handshake-org/hsd/blob/b32c27bbb05e69b86c0e80aea3ecc394c5589186/lib/covenants/rules.js#L1237-L1238

`REGISTER`, `UPDATE`, `RENEW`, `FINALIZE` -> (anything) must have same address:

https://github.com/handshake-org/hsd/blob/b32c27bbb05e69b86c0e80aea3ecc394c5589186/lib/covenants/rules.js#L1281-L1282

`TRANSFER` -> `UPDATE`, `RENEW`, or `REVOKE`:

https://github.com/handshake-org/hsd/blob/b32c27bbb05e69b86c0e80aea3ecc394c5589186/lib/covenants/rules.js#L1330-L1331

### To reproduce:

[I made a quick patch](https://github.com/pinheadmz/hsd/commit/180798b028c44ec19b207cf15b08e824e4150617) that picked a new address for the `REVEAL` transaction and tested the auction process in regtest. The `REVEAL` transaction was accepted by the chain just fine.

### SO.

Should the address unity be enforced for `REVEAL` transactions? Is the address unity provided by the wallet a convenient feature even though its not required? Or could it be removed?

**Comment by boymanjor** [comment]
I do _not_ believe the protocol depends on the address used for the BID covenant matching the address used for the REVEAL. At this point in a name auction, the name (and thus an owner) is not committed to in the urkel tree. The authorization script used to spend the BID does _not_ need to be reused for the REVEAL because it is not a part of the consensus rules. Once the name is registered, an owner is tied to the name and added to the tree. Ownership is tied to the authorization script used in the REVEAL covenant. This is why we enforce that the same address is used.
