### ISSUE TITLE
mempool: reorg => bad-txns-premature-spend-of-coinbase rejection reason

### ISSUE THREAD

**Issue by turbomaze** [handshake-org/hsd#166]
We've observed a half dozen reorgs or so in the last 3 days, which has caused all sorts of interesting error messages. Most of them make sense, but after chatting with @tynes there's still one error I'd like to understand a bit better.

Line: https://github.com/handshake-org/hsd/blob/master/lib/primitives/tx.js#L1311

Presumably, we have not reorged to a shorter (by height) chain that is longer (by work). So if the newly reorged chain is the same length, then shouldn't the input from the coinbase still have matured? Or maybe the tx doesn't have nlocktime set to anything so the miner tried to apply the tx to an earlier block?

I believe the wallet will only pick mature coins, so not clear on the sequence of events that could cause this without wallet funny-business.

**Comment by chjj** [comment]
@turbomaze, is that an error from the mempool or from the chain?

It does look like there were some pretty massive reorgs (100+ blocks). I'm searching log files for weird ones right now (I actually ran into an issue with one of my nodes too, though unrelated to coinbase maturity).

If it's on-chain, the short answer is that rule will only get triggered if someone mines an invalid block, or there is database corruption. I think it's more likely to be the former. [This code][mempool] in particular is supposed to avoid edge cases like that, but maybe it's having some issues. =/

If the error is originating from the mempool, it means the wallet is broadcasting premature coinbase spends, however, it may be doing that because it's on another chain at the moment in the midst of all the reorg craziness.

[mempool]: https://github.com/handshake-org/hsd/blob/master/lib/mempool/mempool.js#L408

**Comment by turbomaze** [comment]
Thanks for the reply. The error originates from the mempool so I suppose that must be it. Fingers crossed mainnet reorgs are smaller than the crazy ones on tn4!
