### ISSUE TITLE
Node ID keys are malleable: preventing connections possible

### ISSUE THREAD

**Issue by pinheadmz** [handshake-org/hsd#315]
h/t @kilpatty for discussion.

### Background

1. hsd nodes have public, static ID keys
2. These keys, along with a node's IP and port, are gossiped between peers in `addr` packets `key@IP:port` (`fullname`)
3. In `HostList` and other `net` modules, peers are only identified by their `IP:port` (`hostname`)
4. When a node has received a `fullname` for a potential peer, it will create a record indexed by the `hostname`, and never update it.

### Issues

1. The `key` provided in the `fullname` could be malleated by an attacker. An attacker could send `addr` packets to the entire network with incorrect `key`'s, and if those messages get to a victim before honest `addr` packets, that victim will never be able to establish outbound connections to the nodes in the attacker's packet.

2. A long-running honest full node operator my update their ID key for some reason. Even though they broadcast their own `key` in `addr` packets they send to their own outbound peers, the issue persists. The old deprecated key will remain in `HostList`'s all over the network, and all inbound connections to this honest full node will fail.

#### 1. Key by `fullname` (potential eclipse attack)

The simplest thing to do here would be just modify anything like `this.map.get(hostname)` in `HostList` and related modules so that a `fullname` is used instead. This means that there will be separate entries for each combination of `key` and `hostname`. 

So these entries would be saved as two separate nodes:
`aaaaa@10.20.30.40:5000`
`bbbbb@10.20.30.40:5000`

If one entry fails, the other might still succeed. They do not cancel each other out and new keys do not replace old keys. Old keys persist, but if they are bad keys, we just don't connect. The behavior would be the same as if we just had a bad IP address.

Drawback: An attacker could spin up one single full node and just modify it to accept connections with a huge battery of keys. An eclipse attack is then possible if a node thinks it's connecting to 8 different entities when really its all the same IP address and port, but different ID keys.

#### 2. Store ID keys in a separate data structure

We could perhaps add a vector to each potential host that stores more than one key. This would be a change to `NetAddress` and might look like this:

```
NetAddress {
  // Store array of keys we have learned about for this address
  this.keys = ['aaaaa', 'bbbbb', ...];

  // Only set this value once a connection has been established.
  // If a connection fails using this key, set it to null and try
  // the next key from the array.
  this.key = 'ccccc';
}
```

#### 3. Switch noise protocol

Handshake currently uses the `XK` variant of noise:

```
XK:
  <- s
  ...
  -> e, es
  <- e, ee
  -> s, se
```

But... do we _even need_ static keys for network nodes? Do we need to authenticate nodes on this network? This makes sense for the Lightning Network where nodes commit to verifiable TXs on chain and sign messages with their ID key, but shouldn't Handshake nodes be homogenous? 

What if we switched to a protocol where we don't need to know anybody's static key for Act One:

```
XX:
  -> e
  <- e, ee, s, es
  -> s, se
```

**Comment by kilpatty** [comment]
Following up here w/ some discussion from the Telegram chat: 

2. and 3. also have some drawbacks. 

2. The main drawback of this strategy is that I can essentially "target" remove nodes from the network. By filling the hostlist of other nodes on the network with invalid keys for a specific node, I increase the probability of that node attempting to connect w/ an invalid key. Since it takes almost nothing to generate invalid keys, this would be a very easy to execute attack - that being said there are definitely some mitigations that we can take to reduce the probability of that happening, but I don't think any of them would solve the problem completely. 

3. Two main drawbacks I see for this. 

A: We lose the secrecy on the first packet to the sender. Honestly I have no idea what that entirely means in this context, but it's something to consider - and perhaps consult with someone who can spell out what exactly that means for us. 

B: Rewrite of Brontide and hostlist (At the least), which isn't truly a drawback, but rather, a consideration to think about in this scenario.

**Comment by turbomaze** [comment]
Crazy idea:

Pick a `k`, store top `k` keys for each key, sorted by some work metric (e.g. grind keys into a particular form). Honest nodes can spend a lot of work `W` on their key to increase the chance they're in peers' top `k`, whereas adversaries must perform `kW` work.

Nodes could even devote some tiny percent of their CPU to always grinding new keys, such that as time goes on, `kW` increases over time.

**Comment by kilpatty** [comment]
> Crazy idea:
> 
> Pick a `k`, store top `k` keys for each ip, sorted by some work metric (e.g. grind keys into a particular form). Honest nodes can spend a lot of work `W` on their key to increase the chance they're in peers' top `k`, whereas adversaries must perform `kW` work.
> 
> Nodes could even devote some tiny percent of their CPU to always grinding new keys, such that as time goes on, `kW` increases.

While I think this is getting to a potential solution here, I'm not sure the best way of making keys expensive to generate is through CPU/hash rate. This would: 

A. Make the upkeep of nodes quite difficult which I think is the opposite idea we are going for w/ hnsd.

B. Give more power to the miners -> I feel like the balance between full nodes and miners is good in that full nodes can hold miners accountable if they cheat. If we give miners the power to "take out" full nodes by using their hash rate to generate bad keys, then I think full nodes loose the balance in that equation. 

That being said, I think coming up with ways of making key generation expensive is a really good potential solution to this problem.

**Comment by tynes** [comment]
> Give more power to the miners

Since the proof of work algorithm is relatively easy to make an asic for, the miners shouldn't be at a huge advantage for creating keys. Somebody could write GPU code or create an asic for creating keys, but I feel like there would be a large opportunity cost there.

I do think the PoW on the keys is an interesting idea but there might be a simpler solution.

**Comment by pinheadmz** [comment]
Yeah this is not a job for PoW in my opinion, it doesn't solve the actual issue and if keys are expensive... only rich people will have keys :-)

Everything we do should be about empowering the single individual user, giving that one human's cheap CPU an advantage over state-level actors with infinite resources. That's the security model of asymmetric cryptography.

**Comment by pinheadmz** [comment]
This is going to be addressed by making Brontide optional, and not gossiping node static ID keys. Since it is still currently an issue, I'll leave this open until a fix is pushed.
