### ISSUE TITLE
Resource Serialization Problems

### ISSUE THREAD

**Issue by tynes** [handshake-org/hsd#431]
Right now, the `Resource` hardcodes in writing its size at 512 instead of using its `getSize` method.

https://github.com/handshake-org/hsd/blob/cb182f47fe9a6d14aa5b6addb59b214dbff705b2/lib/dns/resource.js#L106-L107

This causes an error to be thrown without a good error message when the `Resource` is too large, since the error comes from the `bio` library. 

This is the error message that I am receiving: `EOF (offset=512)`

Other code in the codebase makes the assumption that a `Resource` can serialize to being larger than 512 bytes:

https://github.com/handshake-org/hsd/blob/cb182f47fe9a6d14aa5b6addb59b214dbff705b2/lib/wallet/wallet.js#L2439-L2442

I think a solution to the problem would be to call `resource.getSize` in its `encode` method, and then pad to 512. In the case where it is greater than or equal to 512, add no padding and allow that wallet error to be thrown.

This was motivated by adding a `Resource exceeds maximum size.` error for https://github.com/handshake-org/hsd/pull/429

**Comment by pinheadmz** [comment]
The resource is "sliced" off at its final offset value:

https://github.com/handshake-org/hsd/blob/cb182f47fe9a6d14aa5b6addb59b214dbff705b2/lib/dns/resource.js#L106-L110

See: https://github.com/bcoin-org/bufio/blob/0a97215dd42850957a5316b6d8565e30e5792e6b/lib/staticwriter.js#L108-L122

The wallet error is in a good place, because that is user-facing. Are you thinking we need a similar error in the `resource` module itself for deeper library users?

**Comment by tynes** [comment]
Right now if you call `validateresource` with a Resource that serializes to greater than 512 bytes, you should be able to get a nice error message saying that.

I don't think that the wallet check should be changed, its a good sanity check. In its current form, I don't think that the `Resource exceeds maximum size` error will ever be thrown because an error will be thrown by the `BufferWriter` due to an out of bounds write first.

> The resource is "sliced" off at its final offset value:

You are right about this, I saw the `slice` call with no arguments and read it as being stateless.
