### ISSUE TITLE
Wallet creation of zero-bid transactions 

### ISSUE THREAD

**Issue by randomlogin** [handshake-org/hsd#463]
**Description**: hsw allows creation of zero-bid transaction without any notification that this transaction will not be accepted.

The created transaction can be seen in the wallet's pending transactions list, however the node will not accept it due to dust limits (the transaction itself has nonzero fee), so it will not be seen in node's own mempool and not relayed to anyonel.

**Reproducing**: ```hsw-cli rpc sendbid <name> 0 0```

**Expected behaviour**. Either of these:
1. Tell the user that transaction fails verification, nevertheless create the transaction. 
2. Fail to create the transaction if some special flag like '--ignore-validation-rules` is not passed.

**Related issues**:
#460 Allow bid and lockup with 0 value in wallet-http
#441 wallet: do check covenants for dust in createTX.

**Comment by pinheadmz** [comment]
Thanks @randomlogin 

Issues like this have come up before and it's because bcoin and hsd wallet ignore standardness errors when sending TXs. 

https://github.com/pinheadmz/hsd/blob/bid0/lib/node/fullnode.js#L327-L353

I've never been a fan of this logic, I think it was written for a problem purse had with bcoin?
