### ISSUE TITLE
HIP repository: Handshake Improvement Proposal

### ISSUE THREAD

**Issue by Falci** [handshake-org/hsd#485]
I'd like to suggest a new repo, under handshake-org, where we can submit improvement proposals to handshake.

That would unify and document the community suggestions.

cc @pinheadmz

**Comment by pinheadmz** [comment]
Spawned!

https://github.com/handshake-org/HIPs

This is a totally blank repo, but you (anyone) should be able to open issues and PRs to discuss how we want to manage the Handshake Improvement Proposals.

Some good templates (obviously):

https://github.com/bitcoin/bips

https://github.com/ethereum/EIPs

https://github.com/satoshilabs/slips

My recommendation is that the first PR should be just a README and a `HIP-0000.md` template. You could either copy and modify BIP-1 or just set up a template like SLIP-0000. I recommend markdown (.md) over mediawiki, because that format is intensely irritating and github can preview markdown on the website. Looks like EIP and SLIP have made that choice as well.

After we get the ball rolling, I wouldn't mind opening merge access to the HIP repo to community members that are not already handshake-org members, so if a good custodian emerges they could be added to the team.

I'm going to close this issue and we can move discussion about Handshake Improvement to its new home!

Definitely excited for this effort, I have at least two new Handshake standards I want to propose and get feedback on as soon as we can!

Also pinging @smcki012 who has been interested in starting a HIP repo since the testnet days :-)

**Comment by smcki012** [comment]
Thanks for the lift Matthew! I'll be sure to take a stab at an initial PR ASAP that's a simplified version of the EIP process; one that'll make the work of maintaining the HIP repository as streamlined as possible to go from Community Proposal/Ideation -> Working Draft -> Accepted and Community Vetted Standard, with minimal social overhead. Then perhaps a few of you all can ACK/NACK the PR if it sits well.
