### ISSUE TITLE
chaindb getNameStatus() inserts height if ns is null, breaking ns.isNull()

### ISSUE THREAD

**Issue by pinheadmz** [handshake-org/hsd#497]
I'm not sure if this is going to impact anything but I think it is unexpected behavior.

Expected:

(pseudocode)
```
name = grindName()
ns = FullNode.getNameStatus(name)
assert(ns.isNull())
```

Actual:

the `ns` returned is *almost* null, but it's height is set to the height of the chain + 1:

https://github.com/handshake-org/hsd/blob/d1b42a6a50332ab64de4750297b468de76b05b76/lib/node/fullnode.js#L619-L622

https://github.com/handshake-org/hsd/blob/d1b42a6a50332ab64de4750297b468de76b05b76/lib/blockchain/chaindb.js#L1233-L1237

result:

```
{
  name: '',
  nameHash: '0000000000000000000000000000000000000000000000000000000000000000',
  state: undefined,
  height: 5,
  renewal: 5,
  owner: {
    hash: '0000000000000000000000000000000000000000000000000000000000000000',
    index: 4294967295
  },
  value: 0,
  highest: 0,
  data: '',
  transfer: 0,
  revoked: 0,
  claimed: 0,
  renewals: 0,
  registered: false,
  expired: false,
  weak: false,
  stats: undefined
}
```

This breaks `namestate.js isNull()`:

https://github.com/handshake-org/hsd/blob/d1b42a6a50332ab64de4750297b468de76b05b76/lib/covenants/namestate.js#L107-L121

**Comment by nodech** [comment]
getNameStatus is meant to be consumed by plugins/wallet. This reset in the end unifies the API differences between two cases: Name has expired, so it can be auctioned AND Name that was never on the auction.

Name that has expired will not return empty NS, it will return a namestate that is in the Opening state, I believe that may be side effect of the way chain consumes the namestate. If name reaches processing stage in the chain verification, it is opening automatically and covenant should be OPEN. And another thing: the name does not have specific state for EXPIRED. These two together make a expired name automatically OPENING and only way to make sure from the client that the name is not OPEN and we can send OPEN is basically height check (height = tip.height + 1) (which is okay, ns.isNull() would not help there)
https://github.com/handshake-org/hsd/blob/e3e5e01c395dd56c80d0ff34ba7cfa7854ea79d0/lib/wallet/wallet.js#L1670-L1671

Name that does not exist, will return ns.isNull. Wallets, clients could use this to differentiate names that have been open and Maybe expired, but it's not that useful. maybeExpire + above check of the height will be necessary for proper open and having ns.height set to tip + 1 basically makes the null name same as expired name for the checks.

Note that all auction related names in the wallet have to call ns.maybeExpire because it does not know if the ns came from the server or the local cache. In both cases ns.maybeExpire is necessary to run.

Null names are always expired after height 2196 (treeInterval + biddingPeriod + revealPeriod), so any maybExpire check (which is almost always necessary to run) - will give the name with height at the height of the check.
