### ISSUE TITLE
Submit to hsd testnet node, always return [False, 'stale']

### ISSUE THREAD

**Issue by zhangcongrong** [handshake-org/hsd#524]

**Comment by pinheadmz** [comment]
Handshake has a testnet but there is zero hashrate on it (last I checked), so it's effectively dead.

Related issues: https://github.com/handshake-org/hsd/issues/366 https://github.com/handshake-org/hsd/issues/365

Because this issue affects `getblocktemplate` someone will have to use a different path to generate a testnet block and kick-start the chain. `setgenerate` should still work but may take a while to find a block on a CPU.

I think this issue should be addressed in hsd and then we can just launch another testnet, maybe with much lower difficulty so it can just  be CPU-mined.

**Comment by pinheadmz** [comment]
I'm going to close this issue but feel free to add comments if my answer didn't help.
