### ISSUE TITLE
Contributing: are the eslint rules too lax?

### ISSUE THREAD

**Issue by turbomaze** [handshake-org/hsd#539]
I've noticed that there are various consistent style choices made in this repo that are not reflected in the eslint file. For instance, there is always a space after a semicolon in for loops etc, but there is no `semi-spacing` rule set to `["error", { "before": false, "after": true }]`. There are many such implied style choices like this.

I'm curious to hear about the intended linting/fixing setup and whether or not I'm missing something in my local environment.

Tagging @rozaydin
Tagging @pinheadmz, how does your editor format hsd code?

**Comment by pinheadmz** [comment]
We have https://github.com/handshake-org/hsd/blob/master/CONTRIBUTING.md which recommends to developers to use bslint. I use Sublime Text personally, and I get lint warnings as I type. I also ALWAYS run `npm run lint` before submitting a PR. GitHub CI will also run the linter and ❌   your PR if it fails.

### Ooops, fix this before submitting:

![Screen Shot 2021-01-19 at 10 14 10 AM](https://user-images.githubusercontent.com/2084648/105053579-19f72980-5a3f-11eb-997f-bfa3881db946.png)


So that's my setup and GitHub setup. As far as inconsistencies, I think a PR for style would be great if you have the time to submit. You could add rules to the eslint file, fix lint in the source code, and/or even add additional suggestions in CONTRIBUTING -- not all style rules can be enforced by a linter and we may want to lay out higher-level suggestions in that guide.

**Comment by turbomaze** [comment]
Thanks for the explanation! We'll probably do that
