### ISSUE TITLE
Getting I/O lock error when running with ns-port

### ISSUE THREAD

**Issue by pranay01** [handshake-org/hsd#56]
I get the following error when running  `./bin/hsd --ns-port 5300 ` after starting hsd

```
[info] (chain) Chain is loading.
[info] (chain) Checkpoints are enabled.
[info] (chaindb) Opening ChainDB...
Error: IO error: lock /Users/pranay/.hsd/testnet/chain/LOCK: Resource temporarily unavailable
```

**Comment by boymanjor** [comment]
@pranay01 this is occurring because you are already running a testnet node which is using `~/.hsd/testnet/` as its data directory. To run another testnet node on the same machine you will need to configure the second node to write to a different directory by using the `--prefix` flag, e.g:
```
$ ./bin/hsd --ns-port 5300 --prefix /path/to/dir
```

Note: replace `/path/to/dir` with the desired location of the second data directory.

**Comment by boymanjor** [comment]
I should also add, you won't be able to run the nodes at the same time.
