### ISSUE TITLE
Should HNS root nameserver serve TXT records?

### ISSUE THREAD

**Issue by pinheadmz** [handshake-org/hsd#565]
If you ask a DNS expert, they will tell you "no" without hesitation: the root zone is referral only -- it is not authoritative over the top-level domain and therefore can not answer questions about its records, it can only refer you to that zone. This has already produced discrepancies in user experience like this example:

### `hsd` (with unbound as recursive resolver)

```
$ dig @127.0.0.1 -p 5350 proofofconcept TXT +short
"THIS TXT RECORD IS HOSTED ON MY ACTUAL ZONE!!!"
```

### `hsd --rs-no-unbound` (using `bns` as recursive resolver)

```
$ dig @127.0.0.1 -p 5350 proofofconcept TXT +short
"A simple social network for Handshake"
"support: hs1qde7jaw6qgzzfu83upn3twvsyhh0zrshg76qe0x"
```

The blockchain records are what is returned in the `bns` example:

```
$ hsd-rpc getnameresource proofofconcept
{
  ...
    {
      "type": "TXT",
      "txt": [
        "A simple social network for Handshake"
      ]
    },
    {
      "type": "TXT",
      "txt": [
        "support: hs1qde7jaw6qgzzfu83upn3twvsyhh0zrshg76qe0x"
      ]
    },
  ...
}
``` 

`bns` is able to recover the on chain records directly because it sends a complete request to the HNS root:

```
recursive -> root (query):
  proofofconcept. IN TXT
recursive <- root  (response):
  proofofconcept. IN TXT  "A simple social network for Handshake"
  proofofconcept. IN TXT  "support: hs1qde7jaw6qgzzfu83upn3twvsyhh0zrshg76qe0x"
```

However, unbound (at least the way it is configured by default in hsd) is more private about its queries -- it asks for a referral first and always, then once it knows who is authoritative over the zone it asks _them_ for an answer:

```
recursive -> root (query):
  proofofconcept. IN A
recursive <- root  (response):
  proofofconcept. IN NS ns.proofofconcept
  proofofconcept. IN A 142.93.115.133
recursive -> ns.proofofconcept @142.93.115.133 (query):
  proofofconcept. IN TXT
recursive <- ns.proofofconcept @142.93.115.133 (response):
  proofofconcept. IN TXT  "THIS TXT RECORD IS HOSTED ON MY ACTUAL ZONE!!!"
```

### DNSSEC

Most importantly from DNS' perspective, the TXT from the actual zone's nameserver is signed with DNSSEC and is authoritative. Of course, we know the data on the blockchain is authentic because it came from a valid signed transaction and was confirmed by proof-of-work. But the DNS system doesn't know that.

### HNS "identity" applications

Footnote, Sia links, sinpapeles, and ~Namebase's "login with handshake"~ are examples of applications that rely on users adding some kind of proof string or public key to a TXT on the blockchain. **It is critical that developers understand this:** root zone TXT records must not be queried through DNS, because of the discrepancy described here. If you expect a user to place a TXT in the root zone **you must** rely on hsd internal `getnameresource` API.

For this reason -- I think it is actually safe to enforce standard DNS rules and NOT SERVE TXT from the HNS root server.

Open for discussion !

**Comment by rithvikvibhu** [comment]
Agree, I guess we can confirm with the major apps that they don't depend on blockchain txt via dns before making any changes to this behavior.

**Comment by jacobjonz** [comment]
I agree that the txt record should be removed from the dns response, but can't we still have the record at the root level in the block chain?

**Comment by pinheadmz** [comment]
@jacobhaven absolutely -- the change would ONLY be in the hsd root nameserver

**Comment by pinheadmz** [comment]
Ok I've removed TXT answers from root in #566, so now both with and without `--rs-no-unbound` will query the actual authoritative nameserver for TXT

**Comment by turbomaze** [comment]
Thanks for bringing this up. I think we should keep things as they are.

## End goal

We can probably all agree that our end goal is widespread Handshake adoption :) (or more precisely the adoption of a secure, decentralized alternative to ICANN's root zone)

## Actors

* end users -- random people on the internet that want to use Handshake for something
* Handshake app "happ" developers -- programmers that create apps that involve Handshake

## Assessment

In summary, this PR reduces first-use confusion for end users at the expense of happ developers. I don't think the degree of confusion end-users face is significant whereas the cost to happ developers is noticeable.

### This solution does not scale

This PR seems to imply that happs should exclusively use TXT records stored directly on the blockchain. This means that people who purchase subdomains off of a Handshake TLD (e.g. on registrars like gateway.io) would not be able to use their names. As the number of Handshake users :rocket: :moon:, I expect a significant number of those new users to start out with a Handshake subdomain before graduating to the increasingly scarce root TLDs.

The other sense of "scale" is one name being used for many happs. You only have 512 bytes of space, so maybe now you can fit all your TXT records for the ~3 happs that exist, but if you wanted to use your name for all of the happs that have yet to be created, you would not be able to.

### Sends a confusing message about NS security

This PR seems to imply that blockchain records are somehow more secure than records served from the authoritative NS. When DNSSEC is set up properly, there should be _no difference_ in the degree of trust you have in the NS responses. Uptime differences, sure, but not a trust difference (there are some caveats I'll address if someone fights me on this but I'll stand by this claim).

It's important that end users figure out a way to configure their nameservers securely, since that's where the bulk of their records must be set anyway (remember, we only have 512 bytes on chain). Nameserver security is a requirement for eventual widespread adoption, so we shouldn't be afraid to put records there.

### More steps for happ developers

Right now, if a happ wants to support users with TXT records on the blockchain or in a nameserver, then they just need to query one thing: a Handshake aware DNS resolver. It may seem like a minor difference to ask them to query `rpc getnameresource` to support blockchain TXT users and a DNS resolver to support nameserver TXT users, but that difference is bigger that it appears on the surface.

Running a full node is no joke, and depending on the hosting platform they're using, running something with persistent storage may be an annoying headache. If they only need to query a DNS resolver to support every kind of user, then they can use a public one to get started as they're prototyping, and only commit the mental energy to figuring out their own full node infra after they get users.

### The confusion to end users is minimal

It's easy to go to the user agents through which people are interfacing with Handshake (e.g. Namebase, Bob) and ask them to warn users when they set TXT records on the blockchain. Perhaps a user is confused the first time they run into an issue with a happ they wanted to use, but once they see the warning they wouldn't make that mistake again.

Also, when most people set this stuff up, they're following some set of instructions that's presumably telling them the success path and keeping them away from the footguns.

## Summary

The bulk of the records on Handshake need to be served from a NS anyway, so happs should be built with the assumption that they'll need to perform recursive DNS resolution. Those happs can support users without a namerserver without any additional work if things stay the same as-is, and with proper warnings on the popular user agents, no end user should get confused by this "split-brain authoritative root" issue anyway.

**Comment by jacobjonz** [comment]
/*This means that people who purchase subdomains off of a Handshake TLD (e.g. on registrars like gateway.io) would not be able to use their names. */

Does this really happen. The change is to only remove the txt record from the dns response for the TLD, right? 
For the subdomains, if there are txt records set, those would be in the response for their queries.

Or did I get what you meant wrong?

**Comment by james-stevens** [comment]
**ALL** records that belong to a delegated sub-domain (where an `NS` is present) belong in that sub-domain's zone file. Putting `TXT` records in the ROOT zone along side `NS` records makes no sense. You should have **either** the `NS` **or** the `TXT`, but not both.

If the TLD `app` has TXT record in **both** the zone file & the ROOT zone, which are you going to serve out when asked for `app in txt`? The ones from the ROOT, the ones from the zone-file? Both? If `app` is DNSSEC signed, which keys do you use to sign the `TXT`?

If its a delegated sub-domain, then a resolver will expect the keys in the sub-domain to be used to sign the `TXT` records in that sub-domain.

You shouldn't really just go about breaking all the DNS RFC standards, otherwise it's just not going to work with all the existing s/w that's already out there. So then are you going to re-write the DNS clients & servers everywhere?

We should be trying to leverage as MUCH existing s/w as possible - DNS is huge & really mature, there's  a lot out there.

One suggestion I had was to create the virtual TLD of the single character `ascii(1)` (= Ctrl-A), then `app.[x01] in TXT` could be used to request these hidden TXT records that live in the ROOT & this would probably propagate fine through resolvers. I tested this with `dig` and `8.8.8.8` and it seemed to work.

Or you could just drop the `NS` records. Then the `TXT` are valid in the ROOT zone. Or if they want `NS` records & their own zone file, they put their `TXT` in their zone file.

Standards compliance is the difference between "it works on my laptop" and "it works with the entire internet / what everybody else is doing"

You can't just go breaking standards, becuase you need DANE to work, cos without DANE you have no HTTPS & without HTTPS you have nothing useful - and DANE needs DNSSEC.

The minimum target should be - handshake TLDs are at least as good as ICANN TLDs - that's the minimum, not a "nice to have"

using the bind server I set up as a resolver (with a merged ROOT zone of handshake & ICANN), *ALL* internet application should work with handshake domains (& sub-domains, to any level), inc with DNSSEC - IMHO that should be the target

more would be nice, but that really should be the starting point

Some time ago I went on about standards compliance on telegram, but got the distinct impression nobody really wanted to hear it, so I gave up bothering. It would not be hard to make this workable & scalable, but right now I don't really see it as either cos expecting everybody to run `hsd` on their laptops is just not going to happen.

Having `hsd` built into a browser, means if you haven't used it for a while, it's going to need to catch-up on the blockchain before you can browser - yeah, people will switch that off pretty quickly. And then there's mobile, which is a big proportion of all internet these days.

**Comment by james-stevens** [comment]
> /*This means that people who purchase subdomains off of a Handshake TLD (e.g. on registrars like gateway.io) would not be able to use their names. */
> 
> Does this really happen. The change is to only remove the txt record from the dns response for the TLD, right?
> For the subdomains, if there are txt records set, those would be in the response for their queries.
> 
> Or did I get what you meant wrong?

having TXT records in the ROOT zone & the zone file for the same name creates a conflict, which needs to be resolved.

IF there are `NS` records & therefore a sub-domain zone file, the TXT records in there should take priority

IF the are no NS records, the TXT would be allowed in the ROOT zone & served out

If there are TXT records in both the zone file & ROOT, this proposal suggests giving priority to the TXT in the user's zone file

**Comment by pinheadmz** [comment]
@turbomaze 

> The other sense of "scale" is one name being used for many happs. You only have 512 bytes of space, so maybe now you can fit all your TXT records for the ~3 happs that exist, but if you wanted to use your name for all of the happs that have yet to be created, you would not be able to.

This is precisely what name servers are used for, and the scalability concern is a big part of why the HNS root zone is referral-only. When Namebase users add a "login with handshake" key to their zone, Namebase should put that TXT in the nameserver, not on the blockchain. Think of the scalability boost from that! No blockchain fees, no chain bloat, no urkel tree updates, and you are using DNS properly.

**Comment by turbomaze** [comment]
> /*This means that people who purchase subdomains off of a Handshake TLD (e.g. on registrars like gateway.io) would not be able to use their names. */
> 
> Does this really happen. The change is to only remove the txt record from the dns response for the TLD, right?
> For the subdomains, if there are txt records set, those would be in the response for their queries.
> 
> Or did I get what you meant wrong?

I think this PR wants happ developers to use `rpc getnameresource`, which means that the happs would never even be attempting DNS queries. So records for second-level domains that live on nameservers would not be queried by the happ.

**Comment by pinheadmz** [comment]
@turbomaze @jacobjonz If a name has subdomains, then there MUST be some kind of nameserver somewhere and an NS record on chain. If that name owner also wants to "login with handshake" they should serve their TXT from that nameserver. Problem sovled.

**Comment by turbomaze** [comment]
@james-stevens 
> **ALL** records that belong to a delegated sub-domain (where an `NS` is present) belong in that sub-domain's zone file. Putting `TXT` records in the ROOT zone along side `NS` records makes no sense. You should have **either** the `NS` **or** the `TXT`, but not both.

@pinheadmz
> This is precisely what name servers are used for, and the scalability concern is a big part of why the HNS root zone is referral-only. When Namebase users add a "login with handshake" key to their zone, Namebase should put that TXT in the nameserver, not on the blockchain. Think of the scalability boost from that! No blockchain fees, no chain bloat, no urkel tree updates, and you are using DNS properly.

I think that there's some misunderstanding because I agree with both of you. I don't think anybody should be trying to set TXT records at the root. They should use a nameserver. Resolvers should ignore TXT records if there is a NS record present.

**Comment by pinheadmz** [comment]
@turbomaze so the question is though - for consistency sake, should the root even return TXT if NS is present? Maybe the current no-txt-at-all is too restricitve

**Comment by turbomaze** [comment]
> @turbomaze so the question is though - for consistency sake, should the root even return TXT if NS is present? Maybe the current no-txt-at-all is too restricitve

Yeah I like throwing away TXT if NS is present. I see no sense in having both, it would just cause problems.

I don't see harm in serving TXT from hsd/hnsd if there is no NS though. And if this happens, then happ developers can support those blockchain TXT record end users for free with their normal Handshake-aware resolver.

**Comment by pinheadmz** [comment]
@turbomaze @james-stevens fantastic discussion, friends: https://github.com/handshake-org/hsd/pull/566/commits/d2a31f1af24a335f86bfabf836f61f3b361a2edf

**Comment by james-stevens** [comment]
> @turbomaze
> 
> This is precisely what name servers are used for, and the scalability concern is a big part of why the HNS root zone is referral-only. When Namebase users add a "login with handshake" key to their zone, Namebase should put that `TXT` in the nameserver, not on the blockchain. Think of the scalability boost from that! No blockchain fees, no chain bloat, no urkel tree updates, and you are using DNS properly.

RIGHT!

& ideally they would also DNSSEC sign their TLD's zone file & put a `DS` in the ROOT, so that the `TXT` can be cryptographically validated before being trusted. 

For now `ECDSA384` or `ECDSA256` seems the best ballance of security & broad support in the DNS space, although I have seen some people starting to use Edwards Curve as well, but not on their own - `ED25519` & `ED448` are both in the DNSSEC spec.

The problem with putting a login `TXT` in the zone file & **not** signing it, is you are now going to be trusting untrusted data.

If you put it in the zone file, you could even have per-app `TXT` with stuff like
```
_app1.tld. in txt "key-one"
_app2.tld. in txt "key-two"
```
or whatever

Any TLD that is providing public sub-domains (e.g. selling sub-domains etc) should also really be signed, so that people who buy sub-domains in that TLD can also choose to sign their data, if they wish.

> for consistency sake, should the root even return `TXT` if `NS` is present? Maybe the current no-txt-at-all commit is too restricitve

I think you have two choices.
1. ROOT zone is referral only (`NS` & `GLUE` address records). No exceptions. This is the ICANN policy & the policy of most (all?) ICANN TLDs
2. You can have `TXT`, `A` & `AAAA` in the ROOT **instead** of NS to give people a way of getting up & running faster & easier - some ICANN ccTLDs used to offer this, but I beleive they have mostly stopped.

One problem with (2) is that, by default, `unbound` doesn't support it becuase of a "privacy" feature they have which (IMHO) actually makes no sense and adds almost no privacy. So IMHO, this is more a failure of `unbound` than anything else. Its possible there is a config option to disable it.

But, if there are `NS` & `TXT` (or any other RR type), the RFC says you behave as if the other RRs do not exist. You can still have `A` & `AAAA` as `GLUE` records for the name servers only. In fact, even this is permitted
```
tld. in ns tld.
tld. in a 1.2.3.4
```
In this case the IP Address is `GLUE` & should only be used to retrieve the zone file from `1.2.3.4`, then it should be discarded in favour of the data in the zone file (which *hopefully* is the same anyway!!). Neither record would be served as authoritative (`AA=1`).

So a query for `tld. IN A` should still return a referral - same goes for any other RR type.

---------
As an aside, for those who don't know me, I used to be CTO at dot-IO & CommunityDNS for 10 yrs before IO was sold to Afilias a couple of yrs ago. CommunityDNS is an anycast DNS provider & I wrote the DNS server they use (from scratch, in C). So I know more about DNS that most people would ever want to. I've known Mike Carson for a while as he was & is a dot-IO registrar.
