### ISSUE TITLE
No reveals to redeem.

### ISSUE THREAD

**Issue by sugendran** [handshake-org/hsd#605]
Hi,

I thought I'd try the auction process after going through the airdrop claim process. I created an auction for `sugendran` (vanity name... I know and then managed missed the bid window. Am I right in thinking that all the coins were locked up in the auction creation?

When I try to do the redeem it tells me:
```
No reveals to redeem.
```

Is it possible to recover the coins that were locked up at auction creation?

**Comment by pinheadmz** [comment]
@rithvikvibhu actually OPENs are spendable:

https://github.com/handshake-org/hsd/blob/c861e4fc95f0d023a7da4c90b93dab692b9209d0/lib/primitives/covenant.js#L368-L383

but otherwise you are correct, @sugendran REDEEM is just for losing bids -- winning bids use REGISTER to set DNS records for the name, but it also sweeps the change back from the second-highest bid. In your case (with only one bid) the second highest bid is zero, so when you REGISTER this name you will get your entire reveal amount back as a change output.

**Comment by sugendran** [comment]
Ah okay, I think I misunderstood the output of cli. 

Will close this.
