### ISSUE TITLE
Max Block Requests option

### ISSUE THREAD

**Issue by ul16** [handshake-org/hsd#913]
Whenever it reaches a height of 160,000 it will not accept a set of blocks from any peer for some odd reason. It keeps saying "peer advertised too many blocks" And I looked into it, and there's no option to increase this max block request limit for a given peer connection. I have attached an image about what i'm talking about.
![Screenshot_20241226_210346_Termux](https://github.com/user-attachments/assets/492b56ae-8aba-4570-a598-26ecd32b8d77)

**Comment by nodech** [comment]
The limits are there for DOS and otherwise sanity limits. There's no reason for removing those limits, on the other hand nodes should NOT be sending over that limit. (Note: this is number of headers, not the actual blocks)

What is your node version and what's the version of the peer (or ip if it's public) that is sending those blocks?

It looks like you are using v6.x (Should work fine), but surprising that it starts complaining after 160k (which is checkpoint for v6)

**Comment by nodech** [comment]
Okay, I think I found the issue. Currently you can use `--checkpoints=false` - (makes it slower to sync, but will sync) and you can re-enable the checkpoints again at 165k block. (5k blocks). I will add in-between checkpoint at 200k blocks

**Comment by nodech** [comment]
Thanks for the details, that was the main clue for the issue !

I will be releasing v7.0.1 with the fix. Alternatively, you can disable checkpoints as mentioned above and in the PR.

**Comment by ul16** [comment]
They all are XD it kept connecting to multiple different nodes to get
headers, each one said it send too many

**Comment by nodech** [comment]
> They all are XD it kept connecting to multiple different nodes to get

@ul16 

It should be fixed now! You can upgrade to the latest version. (or disable checkpoints till 175k block)
